### PR TITLE
Added new test cases to increase code coverage

### PR DESCRIPTION
**Pull request by ratnamal**
# What Changed

Add new tests in legacy and modern test files
Fixed an issue where field `forceSingleTheme` is taking boolean value instead of a string in a few tests in legacy.test.ts file

# Why

To increase code coverage

Issue: #18 

Todo:

- [X] Add tests
- [X] Add docs
- [X] Add yourself to contributors (run `yarn contributors:add`)

### CODE REVIEW

**Comment by ratnamal** [comment]
Original coverage:
Coverage on master branch

Coverage after adding tests:
Coverage after adding tests

**Review by tylerkrupicka — APPROVED** [review]
Thanks for the contribution! This is looking great.

Can you fix the conflicts (we had some new contributors), and then I can merge.

**Comment by ratnamal** [comment]
> Thanks for the contribution! This is looking great.
> 
> Can you fix the conflicts (we had some new contributors), and then I can merge.

@tylerkrupicka Fixed the merge conflicts

**Comment by hipstersmoothie** [comment]
:rocket: PR was released in v2.1.0 :rocket:

**Pull request merged**
