### PR TITLE
refactor: restructure plugin layout for better separation

### PR DESCRIPTION
**Pull request by joshtym**
# What Changed
Taking a stab at #20 by splitting the configuration into 4 primary components: common, legacy, modern and types

# Why
See issue for the why

Todo:

- [ ] Add tests
- [ ] Add docs
- [ ] Add yourself to contributors (run `yarn all-contributors add [name] [type]`) see https://github.com/all-contributors/all-contributors/blob/master/docs/cli/usage.md

### CODE REVIEW

**Comment by tylerkrupicka** [comment]
Hey @joshtym, I took a glance at this and it looks great! I'll do a more thorough review soon. Thanks for contributing!

**Review by tylerkrupicka — APPROVED** [review]
This looks good to me! Can you fix the conflicts and then ill work on getting this in?

**Comment by joshtym** [comment]
> This looks good to me! Can you fix the conflicts and then ill work on getting this in?

Done!

**Review by tylerkrupicka — APPROVED** [review]

**Comment by hipstersmoothie** [comment]
:rocket: PR was released in v2.2.1 :rocket:

**Comment by tylerkrupicka** [comment]
Thanks for the contribution @joshtym!

**Pull request merged**
