### PR TITLE
Added logo gif

### PR DESCRIPTION
**Pull request by Sharps**
Regarding #19

So I had an idea for a logo that might work for you. It's a gif that's somewhat "changing themes".
I never did a pull request before today, just messing around for the hacktoberfest thing. Not sure what's the best way to upload the file for the readme but I just added a imgur link for now.

Hope this is helpful.

### CODE REVIEW

**Comment by hipstersmoothie** [comment]
This looks great! I like the logo a lot. Could you move the image into the repo? you should then be able to use a relative path to reference it in the readme

**Comment by tylerkrupicka** [comment]
Agree with Andrew. Logo looks great, just move it into the repo, maybe make an `images` folder. Could also maybe be a little bigger!

**Comment by Sharps** [comment]
Made it a bit bigger, added to "images" folder and changed the path on the readme. Hope that works.

**Comment by tylerkrupicka** [comment]
Hey @Sharps thanks again for the contribution, unfortunately, we had multiple people contribute logos that we like which put us in a tough spot. We decided, to add a contributed image logo to the ReadMe, but I still want to find a place to use yours and recognize the work you put in.

I made https://github.com/intuit/postcss-themed/pull/33, which added your GIF to the codebase, and added you as a contributor in the ReadMe. We'll likely be using your animation in our Contributing.md when we create it!

Hopefully, that all works for you. Again I want to emphasize how thankful we are for your work -- we'll make sure it gets used.

**Pull request closed without merging**
